version: "3"
services:
  tomcat:
    ports:
      - "8081:8080"
    image: tomcat:10.1-jdk17
    volumes:
      - ./target:/usr/local/tomcat/webapps
    environment:
      - JAVA_OPS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080